
###############################################################
User Api
###############################################################


POST http://localhost:5000/api/users/register
content-Type: application/json

{
    "name": "a",
    "email": "a@gmail.com",
    "password": "a"
}

###

POST http://localhost:5000/api/users/login
content-Type: application/json

{
    "email": "a@gmail.com",
    "password": "a"
}

###
GET http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTZkM2U0N2ZhNjJjODc0NDcyN2VlMSIsImlhdCI6MTY1NDA1MjgzNywiZXhwIjoxNjU2NjQ0ODM3fQ.BzkkscM6EmkSnWqugu-CSTlKNdSZSB55Aea_p7pEBfk

###

PUT http://localhost:5000/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTZkM2U0N2ZhNjJjODc0NDcyN2VlMSIsImlhdCI6MTY1NDA1MjgzNywiZXhwIjoxNjU2NjQ0ODM3fQ.BzkkscM6EmkSnWqugu-CSTlKNdSZSB55Aea_p7pEBfk
content-Type: application/json

{
    "name": "a",
    "email": "a@gmail.com",
    "password": "a"
}


###

Admin Operations

###

POST http://localhost:5000/api/users/login
content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin"
}

###

GET http://localhost:5000/api/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDBlZDcyMmY2ZDMzNDRkMjRiNjZjNCIsImlhdCI6MTY1Nzg5Njc3NiwiZXhwIjoxNjYwNDg4Nzc2fQ.85W-Ht5WqQDUweZ78jsc4xz5VA3wLVu2LvUQ8OVQ4NE

###

GET http://localhost:5000/api/users/6296d3e47fa62c8744727ee1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTZkOWQ0MzhhNzM3MjJiNzFiNWU5OCIsImlhdCI6MTY1NDA1MzM4OSwiZXhwIjoxNjU2NjQ1Mzg5fQ.mSWR38-opqEDyVEEka9nALGhgja-DlyAxTB1zp1G2qM

###
PUT http://localhost:5000/api/users/62d1a206ba228e9c52c5c0b2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDBlZDcyMmY2ZDMzNDRkMjRiNjZjNCIsImlhdCI6MTY1Nzg5Njc3NiwiZXhwIjoxNjYwNDg4Nzc2fQ.85W-Ht5WqQDUweZ78jsc4xz5VA3wLVu2LvUQ8OVQ4NE
content-Type: application/json

{
    "name": "a",
    "email": "a@gmail.com",
    "password": "a",
    "isAdmin":true
}

###

DELETE http://localhost:5000/api/users/62cab1168ce41d6c9b58353f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTZkOWQ0MzhhNzM3MjJiNzFiNWU5OCIsImlhdCI6MTY1NzQ1MDk5NCwiZXhwIjoxNjYwMDQyOTk0fQ.rwr9YSljnf6BLGNvt6ZPF6FzSrsKql4gBCFxDNUHak0



###############################################################
Product Api
###############################################################


GET http://localhost:5000/api/product/

###

POST http://localhost:5000/api/product/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyZDBlZDcyMmY2ZDMzNDRkMjRiNjZjNCIsImlhdCI6MTY1Nzg5Njc3NiwiZXhwIjoxNjYwNDg4Nzc2fQ.85W-Ht5WqQDUweZ78jsc4xz5VA3wLVu2LvUQ8OVQ4NE
content-Type: application/json

{
    "name":"y",
    "price":0,
    "description":"Dress",
    "categories":["women"],
    "sizes":["M","L"],
    "images":[]
}

###

GET http://localhost:5000/api/product/629784dde601eeb3781985df

###

PUT http://localhost:5000/api/product/62cb10282f5e3cb76b1c1ed9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTZkOWQ0MzhhNzM3MjJiNzFiNWU5OCIsImlhdCI6MTY1NzQ1MDk5NCwiZXhwIjoxNjYwMDQyOTk0fQ.rwr9YSljnf6BLGNvt6ZPF6FzSrsKql4gBCFxDNUHak0
content-Type: application/json

{
    "name":"AAYU dress",
    "price":1800,
    "description":"Women Fit and Flare Black Dress",
    "categories":["women","tops"],
    "sizes":["M","L","XL"],
    "images":[],
    "countInStock":8
}

###

POST http://localhost:5000/api/product/629784dde601eeb3781985df/reviews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTZkYmY2ZGY1YzM0YzIyMzA1ODc0ZSIsImlhdCI6MTY1NDA5Nzc3NiwiZXhwIjoxNjU2Njg5Nzc2fQ.qdJHgEEp_JKq6iQ1cLQ3oacEn6l7LJIz1dk-MCZxa1s
content-Type: application/json

{
    "rating":4,
    "comment": "nice look and good fitting"
}

###

DELETE http://localhost:5000/api/product/62cb0b3a2f5e3cb76b1c1eb8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyOTZkOWQ0MzhhNzM3MjJiNzFiNWU5OCIsImlhdCI6MTY1NzQ3NDM4NywiZXhwIjoxNjYwMDY2Mzg3fQ.11564ZoPpok-bEPoi66ING5Ow_HOTAa6SoIv7v5qI-I




